version: '3.5'

volumes:
  local_postgres_data: {}

services:
  postgres:
    image: postgres:latest
    container_name: crud-traits-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-crud-traits}
      POSTGRES_USER: ${POSTGRES_USER:-crud-traits}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
