[package]
name = "crud-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.60"

[dev-dependencies]
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "postgres"] }
